# Generated by Django 4.2.6 on 2023-11-04 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PresetAreas",
            fields=[
                ("bbox_lon1", models.FloatField(blank=True, null=True)),
                ("bbox_lat1", models.FloatField(blank=True, null=True)),
                ("bbox_lon2", models.FloatField(blank=True, null=True)),
                ("bbox_lat2", models.FloatField(blank=True, null=True)),
                (
                    "tag",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name="SatteliteImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bbox_lon1", models.FloatField(blank=True, null=True)),
                ("bbox_lat1", models.FloatField(blank=True, null=True)),
                ("bbox_lon2", models.FloatField(blank=True, null=True)),
                ("bbox_lat2", models.FloatField(blank=True, null=True)),
                ("x", models.FloatField(blank=True, null=True)),
                ("y", models.FloatField(blank=True, null=True)),
                ("zoom", models.FloatField(blank=True, null=True)),
                ("time_start", models.DateField(blank=True, null=True)),
                ("time_end", models.DateField()),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("SENTINEL2_L2A", "Sentinel2_L2A"),
                            ("SENTINEL2_L1C", "Sentinel2_L1C"),
                        ],
                        max_length=50,
                    ),
                ),
                ("original_image", models.ImageField(upload_to="images/")),
                ("annotated_image", models.ImageField(upload_to="images/")),
                ("ships_data", models.JSONField()),
                ("n_total_ships", models.PositiveIntegerField()),
                ("n_navy", models.PositiveIntegerField()),
                ("n_oil_tanker", models.PositiveIntegerField()),
                ("n_cargo", models.PositiveIntegerField()),
                ("n_fishing", models.PositiveIntegerField()),
                ("n_boat", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=250)),
                ("date_fetched", models.DateTimeField(auto_now_add=True)),
                (
                    "Area_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="area_tag",
                        to="fetch_data.presetareas",
                    ),
                ),
            ],
        ),
    ]
