# Generated by Django 4.2.6 on 2023-11-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="satteliteimages",
            name="annotated_image",
        ),
        migrations.RemoveField(
            model_name="satteliteimages",
            name="id",
        ),
        migrations.RemoveField(
            model_name="satteliteimages",
            name="n_boat",
        ),
        migrations.RemoveField(
            model_name="satteliteimages",
            name="n_cargo",
        ),
        migrations.RemoveField(
            model_name="satteliteimages",
            name="n_fishing",
        ),
        migrations.RemoveField(
            model_name="satteliteimages",
            name="n_navy",
        ),
        migrations.RemoveField(
            model_name="satteliteimages",
            name="n_oil_tanker",
        ),
        migrations.RemoveField(
            model_name="satteliteimages",
            name="n_total_ships",
        ),
        migrations.RemoveField(
            model_name="satteliteimages",
            name="original_image",
        ),
        migrations.RemoveField(
            model_name="satteliteimages",
            name="ships_data",
        ),
        migrations.AddField(
            model_name="satteliteimages",
            name="image_path",
            field=models.URLField(default="Unknown", primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="SatteliteImageObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annotated_image", models.ImageField(upload_to="images/")),
                ("ships_data", models.JSONField()),
                ("n_total_ships", models.PositiveIntegerField()),
                ("n_navy", models.PositiveIntegerField()),
                ("n_oil_tanker", models.PositiveIntegerField()),
                ("n_cargo", models.PositiveIntegerField()),
                ("n_fishing", models.PositiveIntegerField()),
                ("n_boat", models.PositiveIntegerField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_id",
                        to="fetch_data.satteliteimages",
                    ),
                ),
            ],
        ),
    ]
