# Generated by Django 4.2.6 on 2023-11-12 09:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0002_alter_presetarea_x_max_alter_presetarea_x_min_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long", models.FloatField()),
                ("lat", models.FloatField()),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("z", models.IntegerField()),
                ("time_from", models.DateField()),
                ("time_to", models.DateField()),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("length", models.FloatField(blank=True, null=True)),
                ("awake", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WaterCraft",
            fields=[
                (
                    "name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("length_min", models.FloatField()),
                ("length_max", models.FloatField()),
                ("color", models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name="satteliteimage",
            name="annotated_image_path",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="satteliteimage",
            name="time_from",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="satteliteimage",
            name="time_to",
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name="SatteliteImageObject",
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_id",
                to="fetch_data.satteliteimage",
            ),
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="object_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detected_objects",
                to="fetch_data.watercraft",
            ),
        ),
    ]
