# Generated by Django 4.2.6 on 2023-11-05 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0003_presetareas_x_max_presetareas_x_min_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PresetAreas",
            new_name="PresetArea",
        ),
        migrations.RenameModel(
            old_name="SatteliteImages",
            new_name="SatteliteImage",
        ),
        migrations.RenameModel(
            old_name="SatteliteImageObjects",
            new_name="SatteliteImageObject",
        ),
    ]
