# Generated by Django 4.2.6 on 2023-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0004_rename_long_detectedobject_lon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordsMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lon_min", models.FloatField()),
                ("lon_max", models.FloatField()),
                ("lat_min", models.FloatField()),
                ("lat_max", models.FloatField()),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("zoom", models.IntegerField()),
            ],
        ),
    ]
