# Generated by Django 4.2.6 on 2023-11-05 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0005_remove_presetarea_z_presetarea_zoom_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name='SatteliteImage',
            old_name='time_start',
            new_name='time_from',
    ),
        migrations.RenameField(
            model_name='SatteliteImage',
            old_name='time_end',
            new_name='time_to',
    ),
    ]