# Generated by Django 4.2.6 on 2023-11-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0006_alter_satteliteimage_zoom_queuedtasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedtasks",
            name="task_id",
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
