# Generated by Django 4.2.6 on 2023-11-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0009_remove_presetarea_bbox_lat1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presetarea",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presetarea",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presetarea",
            name="width",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
