# Generated by Django 4.2.6 on 2023-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0010_presetarea_area_presetarea_height_presetarea_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presetarea",
            name="area",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="presetarea",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="presetarea",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
