# Generated by Django 4.2.6 on 2023-11-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0011_alter_presetarea_area_alter_presetarea_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presetarea",
            name="area",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
