# Generated by Django 4.2.6 on 2023-11-22 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0012_alter_presetarea_area"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detectedobject",
            name="x",
        ),
        migrations.RemoveField(
            model_name="detectedobject",
            name="y",
        ),
        migrations.RemoveField(
            model_name="detectedobject",
            name="zoom",
        ),
    ]
