# Generated by Django 4.2.6 on 2023-11-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0013_remove_detectedobject_x_remove_detectedobject_y_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presetarea",
            name="x_max_z14",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presetarea",
            name="x_min_z14",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presetarea",
            name="y_max_z14",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presetarea",
            name="y_min_z14",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
