# Generated by Django 4.2.6 on 2023-11-25 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fetch_data", "0014_presetarea_x_max_z14_presetarea_x_min_z14_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QueuedTasks",
            new_name="QueuedTask",
        ),
        migrations.AddField(
            model_name="detectedobject",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="detected_objects",
                to="fetch_data.queuedtask",
            ),
        ),
    ]
