# Generated by Django 4.2.6 on 2023-11-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0016_rename_area_tag_satteliteimage_area_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectedobject",
            name="lat",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="detectedobject",
            name="lon",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="detectedobject",
            name="time_from",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="detectedobject",
            name="time_to",
            field=models.DateField(null=True),
        ),
    ]
