# Generated by Django 4.2.6 on 2023-11-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "fetch_data",
            "0017_alter_detectedobject_lat_alter_detectedobject_lon_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedtask",
            name="parent_task_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="queuedtask",
            name="area_tag",
        ),
        migrations.AddField(
            model_name="queuedtask",
            name="area_tag",
            field=models.ManyToManyField(null=True, to="fetch_data.presetarea"),
        ),
    ]
