# Generated by Django 4.2.6 on 2023-11-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0019_alter_queuedtask_area_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedtask",
            name="is_parent",
            field=models.BooleanField(null=True),
        ),
    ]
