# Generated by Django 4.2.6 on 2023-11-27 04:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0022_remove_queuedtask_parent_task_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queuedtask",
            old_name="childs_task_ids",
            new_name="childs_tasks",
        ),
    ]
