# Generated by Django 4.2.6 on 2023-11-27 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0023_rename_childs_task_ids_queuedtask_childs_tasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="queuedtask",
            old_name="childs_tasks",
            new_name="child_task",
        ),
    ]
