# Generated by Django 4.2.6 on 2023-11-28 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0025_remove_detectedobject_task_detectedobject_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedtask",
            name="time_queued",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2023, 11, 28, 13, 56, 42, 851018)
            ),
        ),
    ]
