# Generated by Django 4.2.6 on 2023-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0028_queuedtask_inference_result_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedtask",
            name="time_queued",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
