# Generated by Django 4.2.6 on 2023-11-29 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0029_alter_queuedtask_time_queued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedtask",
            name="time_queued",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2023, 11, 29, 10, 55, 28, 646415, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
