# Generated by Django 4.2.6 on 2023-11-29 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0030_alter_queuedtask_time_queued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedtask",
            name="time_queued",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 29, 11, 6, 32, 184431, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
