# Generated by Django 4.2.6 on 2023-11-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0032_alter_queuedtask_time_queued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedtask",
            name="time_queued",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
