# Generated by Django 4.2.6 on 2023-12-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0033_alter_queuedtask_time_queued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedtask",
            name="task_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
