# Generated by Django 4.2.6 on 2023-12-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0034_alter_queuedtask_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalVariables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_task_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="queuedtask",
            name="task_id",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
