# Generated by Django 4.2.6 on 2023-12-10 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fetch_data", "0035_internalvariables_alter_queuedtask_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedtask",
            name="confidence_threshold",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
